replicas: 1

kafkaResources:
  requests:
    memory: 1Gi
    cpu: "100m"
  limits:
    memory: 2Gi
    cpu: "1"

kafkaStorage:
  size: "1Gi"

kafkaConfig:
  offsets.topic.replication.factor: 1
  transaction.state.log.replication.factor: 1
  transaction.state.log.min.isr: 1
  log.message.format.version: "2.7"
  inter.broker.protocol.version: "2.7"

zookeeperResources:
  requests:
    memory: 128Mi
    cpu: "100m"
  limits:
    memory: 1Gi
    cpu: "1"

zookeeperStorage:
  size: "1Gi"