apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "frontendapi.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontendapi.name" . }}
  action: ALLOW
  rules:
  - {}