{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "web.fullname" . }}
spec:
  hosts:
  - jellebens.ddns.net
  gateways:
  - moneta
  http:
    # - match:
    #     - uri:
    #         prefix: /.well-known/acme-challenge/ 
    #   route:
    #     - destination:
    #         port:
    #           number: 8089
    #         host: cm-acme-http-solver-778x4.istio-system.svc.cluster.local
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: {{ $svcPort }}
            host: {{ include "web.fullname" . }}