apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ap-allow-instruments-service
spec:
  selector:
    matchLabels:
      app: "mssql"
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/moneta/sa/instruments"]
    to:
      - operation:
          ports: ["1433"]
