apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mssql-internal
spec:
  hosts:
  - mssql
  ports:
  - name: tcp
    number: 1433
    protocol: tcp
  location: MESH_INTERNAL