apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}
  labels:
    app: mssql
spec:
  selector:
    app: mssql
  ports:
    - name: mssql-tcp
      protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
