// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionService.Sql;

namespace TransactionService.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    partial class TransactionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TransactionService.Domain.Amount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Exchangerate")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)")
                        .HasColumnName("Exchangerate");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("amount", "transactions");
                });

            modelBuilder.Entity("TransactionService.Domain.BuyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountId");

                    b.Property<Guid?>("AmountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("Number");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Symbol");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("AccountId", "Number")
                        .IsClustered();

                    b.HasIndex("AmountId");

                    b.ToTable("buyorder", "transactions");
                });

            modelBuilder.Entity("TransactionService.Domain.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 5)
                        .HasColumnType("decimal(19,5)")
                        .HasColumnName("Amount");

                    b.Property<Guid?>("BuyorderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("BuyorderId");

                    b.ToTable("costs", "transactions");
                });

            modelBuilder.Entity("TransactionService.Domain.BuyOrder", b =>
                {
                    b.HasOne("TransactionService.Domain.Amount", "Amount")
                        .WithMany()
                        .HasForeignKey("AmountId");

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("TransactionService.Domain.Cost", b =>
                {
                    b.HasOne("TransactionService.Domain.BuyOrder", "Buyorder")
                        .WithMany("Costs")
                        .HasForeignKey("BuyorderId");

                    b.Navigation("Buyorder");
                });

            modelBuilder.Entity("TransactionService.Domain.BuyOrder", b =>
                {
                    b.Navigation("Costs");
                });
#pragma warning restore 612, 618
        }
    }
}
