apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noip-tls-cert-v2
  namespace: istio-system
spec:
  secretName: noip-tls-cert-v3
  issuerRef:
    name: letsencrypt
  commonName: jellebens.ddns.net
  dnsNames:
  - jellebens.ddns.net
