apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "web.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web.name" . }}
  action: ALLOW
  rules:
  - to:
    - operation:
        paths: ["/*"]